server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://hankoserver:13306/hankofw?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: hankdb
    password: xxxxx
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5

  redis:
    host: hankoserver # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 16379 # Redis服务器连接端口
    password: xxxxx  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
